# Generated by Django 4.2.1 on 2026-04-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('body_type', models.CharField(max_length=50, verbose_name='Тип кузова')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN-код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='cars_car_time_cr_b3586b_idx'), models.Index(fields=['slug'], name='cars_car_slug_bb2819_idx'), models.Index(fields=['brand'], name='cars_car_brand_ea0aa7_idx')],
            },
        ),
    ]
