# Generated by Django 4.2.1 on 2026-04-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carcategory_carengine_cartag_car_category_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.carcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
