# Generated by Django 4.2.1 on 2026-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/photos/%Y/%m/%d/', verbose_name='Фото автомобиля'),
        ),
    ]
